### ISSUE TITLE
Force closes immediately 

### ISSUE THREAD

**Issue by Elitpecs** [sean111/terrariahb#10] opened 2011-12-06 23:36 UTC
I am using Samsung Galaxy S Vibrant with ANDROID 2.2. No updtes past 2.2 are available yet, so updating that is out. Before your recebt update that has terraria 1.1 info, it worked perfectly fine. However, whenever I launch it now it just force closes. The most I got from the error is:
 File://android_assets/www/index.html

**Comment by sean111** [comment] 2011-12-07 15:16
For the 0.5.0 release I updated Phonegap to 1.2.0 which seems to be causing the issue. Also in my testing I overlooked setting up a 2.2 emulator. I am working on downgrading to Phonegap 1.0.0 and have a 2.2 emulator now in place for testing. I hope to have a fix out before 12pm EST.

**Comment by sean111** [comment] 2011-12-07 15:49
Turns out the issue isn't with the Phonegap version but with Android OS. 

Data exceeds UNCOMPRESS_DATA_MAX (5145352 vs 1048576) 

Looking for a fix now

**Comment by Elitpecs** [comment] 2011-12-07 16:46
Okay awesome look forward to getting it fixed!

**Comment by sean111** [comment] 2011-12-07 20:42
I just uploaded the new apk. Will wait till tonight to close the issue in case but it was running very well on the 2.2 emulator.

**Closed as completed** 2011-12-08 10:11 UTC
Labels: Major Issue
