### ISSUE TITLE
1.2.x updates

### ISSUE THREAD

**Issue by PavelCech** [sean111/terrariahb#20] opened 2014-08-10 09:41 UTC
Please start updating your wiki to terraria 1.2 versions. There are missing even some of the most common enemies.

**Comment by MoohmadToom** [comment] 2014-09-11 11:13
Update the game🙏

**Comment by sean111** [comment] 2014-09-11 12:34
Duplicate of #19 

I am starting to look into ways to update the app.

**Closed as completed** 2014-09-11 12:33 UTC
